config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  post '/' => 'home#calculate', as: 'calculate'
  resources :people, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  enum gender: { male: 0, female: 1 }

  validates :height, presence: true, numericality: true
  validates :weight, presence: true, numericality: true
  validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def calculate
    @gender = Classifier::PeopleGenderClassifier.new(
      weight: person[:weight].to_i,
      height: person[:height].to_i
    ).classify
    render 'index'
  rescue Classifier::Error => e
    @error = e
    render 'index'
  end

  private

  def person
    params[:person]
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:weight, :height, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
p Gender Classifier

= form_for :person, as: :post, url: calculate_path do |f|
  div.field
    = f.label :weight
    br
    = f.text_field :weight
  div.field
    = f.label :height
    br
    = f.text_field :height
  div.actions
    = f.submit 'Predict Gender'

- if @error
  = @error
- elsif @gender
  p GENDER:
  p = @gender

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title GenderClassifier
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = link_to 'Gender Classifier', root_path, class: 'button'
    = link_to 'Test data', people_path, class: 'button'
    = yield

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.full_messages.any?
    - @person.errors.full_messages.each do |error_message|
      = error_message if @person.errors.full_messages.first == error_message
  div.field
    = f.label :weight
    br
    = f.text_field :weight
  div.field
    = f.label :height
    br
    = f.text_field :height
  div.field
    = f.label :gender
    br
    = f.select :gender, Person.genders.keys
  div.actions
    = f.submit

app/views/people/edit.html.slim
p Edit person data
= render partial: 'form'

app/views/people/index.html.slim
p List of People
p
  table
    thead
      tr
        th height
        th weight
        th gender
        th
        th
    tbody
      - @people.each do |person|
        tr
          td = person.height
          td = person.weight
          td = person.gender
          td = link_to 'Edit', edit_person_path(person.id)
          td = link_to 'Delete', person_path(person.id), method: :delete


p
  = link_to 'New person', new_person_path, class: 'button'

app/views/people/new.html.slim
= form_for @person do |f|
  div.field
    = f.label :weight
    br
    = f.text_field :weight
  div.field
    = f.label :height
    br
    = f.text_field :height
  div.field
    = f.label :gender
    br
    = f.select :gender, Person.genders.keys
  div.actions
    = f.submit